target-version="py38"
line-length = 130

preview = true

[format]
quote-style = "single"
indent-style = "space"

[lint]
select = [
    "E", "F", "UP", "B", "I", "FA102",
    "A", "C4", "PIE", "PT", "PTH", "RET", "RSE", "RUF"
]

ignore = [
    "UP007", "ANN002", "ANN003", "ANN101", "ANN102",
]
