target-version="py39"
line-length = 120

[format]
quote-style = "single"
indent-style = "space"

[lint]
select = [
    "ANN",
    
    "E", "F", "UP", "B", "SIM", "I", "FA102",
    "A", "C4", "PIE", "PT", "PTH", "RET", "RSE", "RUF"
]

ignore = [
    "UP007", "ANN002", "ANN003", "ANN101", "ANN102",
]
